name: ci

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configurar Node
      uses: actions/setup-node@v4
      with:
        node-version: '21' 

    - name: Instalar dependencias
      run: |
        pip install -r vote/requirements.txt
        cd result && npm install && cd ..
        cd worker && npm install && cd ..

    - name: Ejecutar tests App Vote
      working-directory: ./vote
      run: |
        pytest tests/ -v || echo "❌ Fallaron los vote tests"

    - name: Ejecutar tests App Result
      working-directory: ./result
      run: |
        npm run test || echo "❌ Fallaron los result tests"

    - name: Ejecutar tests App Worker
      working-directory: ./worker
      run: |
        npm run test || echo "❌ Fallaron los worker tests"

  unit-test-integration:
    runs-on: [self-hosted, staging]
    needs: unit-tests
    steps:
    - name: Construir servicios
      run: docker compose -f docker-compose.yml up -d

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Unit Test Integration
      working-directory: ./scripts
      run: |
        pip install -r requirements.txt
        python integration_test.py
