name: CI

on:
  push:
    branches: [master, feature/pipeline_test]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configurar Node
      uses: actions/setup-node@v4
      with:
        node-version: '21' 

    - name: Instalar dependencias
      run: |
        pip install -r vote/requirements.txt
        cd result && npm install && cd ..
        cd worker && npm install && cd ..

    - name: Ejecutar tests
      run: |
        pytest vote/tests/ -v || echo "❌ Fallaron los vote tests"
        cd result && npm run test && cd .. || echo "❌ Fallaron los result tests"
        cd worker && npm run test && cd .. || echo "❌ Fallaron los worker tests"