name: deploy_production

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: [self-hosted, production]
    environment:
      name: production
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Notificar a Discord Aprobación
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\":\":hourglass: Esperando aprobación para desplegar *${github.repository}* a *producción*\"}" \
          $DISCORD_WEBHOOK

    - name: Parar servicios anteriores
      run: docker compose down -v || true

    - name: Levantar servicios
      run: docker compose -f docker-compose.production.yml up -d --build

    - name: Ver estado de contenedores
      run: docker ps -a

    - name: Verificar app Result
      run: |
        for i in {1..15}; do
          curl -sf http://localhost:3000/healthz && break
          echo "Esperando servicio en http://localhost:3000/healthz"
          sleep 2
        done

    - name: Verificar app Vote
      run: |
        for i in {1..15}; do
          curl -sf http://localhost/healthz && break
          echo "Esperando servicio en http://localhost/healthz"
          sleep 2
        done


    - name: Notificar a Discord
      if: success()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\":\":rocket: Despliegue exitoso en *producción* por *${github.actor}*\"}" \
          $DISCORD_WEBHOOK